### ISSUE TITLE
`FullSubnetLaplace.sample()` doesn't use `generator`

### ISSUE THREAD

**Issue by elcorto** [aleximmer/Laplace#213]
Hi

I was doing some reproducibility tests for `pred_type="nn"`, so testing `SomeLaplaceClass._nn_predictive_samples()` -> `SomeLaplaceClass.sample()`, using the current `main` (508843dbc37498e02ef421a573e7c546a90a9443).

I found that `FullSubnetLaplace.sample()` doesn't use the passed `generator` (`ruff check --select ARG laplace/subnetlaplace.py` also catches this). The reason is probably that the used `torch.distributions.MultivariateNormal` doesn't offer an API to pass in a `generator`.

I guess it would not be too difficult to rewrite this in the way other sample methods do things -- generate and re-use a set of standard Normal samples (because of #91) and go from there.

Thanks.

**Comment by wiseodd** [comment]
Hi Steve, thanks for catching this.

I agree, the fix is super simple as you mentioned. Probably could also be as simple as reusing `super().sample()`.

I have to admit that we don't pay too much attention to the `SubnetLaplace` implementation anymore since the same can be done more intuitively by switching off the unwanted subset's grads. The benefit of the latter is that the Jacobian for the linearized predictive will only be computed over the selected subset. Meanwhile, the former computes the *full* Jacobian first and then slices it using the subnet indices.

In any case, happy to accept your PR, as always!

**Comment by elcorto** [comment]
> Hi Steve, thanks for catching this.
> 
> I agree, the fix is super simple as you mentioned. Probably could also be as simple as reusing `super().sample()`.

I put together a fix, please see #216.

> I have to admit that we don't pay too much attention to the `SubnetLaplace` implementation anymore since the same can be done more intuitively by switching off the unwanted subset's grads. The benefit of the latter is that the Jacobian for the linearized predictive will only be computed over the selected subset. Meanwhile, the former computes the _full_ Jacobian first and then slices it using the subnet indices.

I have some questions regarding this method but this is off-topic for this issue particular issue here, so I'll open a new one.
