### ISSUE TITLE
Usage for Object Detection

### ISSUE THREAD

**Issue by ssakhavi** [AlexImmer/Laplace#53]
Hi

Love the work you're doing. 

A Question: are the algorithms in this repo agnostic to the downstream task or the type of input? 
For example, if I have an object recognition model for LIDAR data or classification of Audio inputs, can I still use the package?

**Comment by AlexImmer** [comment]
Hi. Thanks, Siavash.

We are currently working on enabling custom data loaders which means the package should allow any type of input in the future as long as the neural network applied is fairly standard. Regarding outputs, object detection could be tricky unless you cast it as something like a regression problem on 2D. That is because we currently only implement regression or classification.

**Comment by ssakhavi** [comment]
Thanks Alex. 

Will definitely try this for my upcoming projects.
