### ISSUE TITLE
How to use when a regression model predicts mean and variance

### ISSUE THREAD

**Issue by hnisonoff** [AlexImmer/Laplace#78]
Can Laplace support regression models that output a mean and a variance? Thanks for package!

**Comment by AlexImmer** [comment]
Generally, this should be possible and we also plan to add such feature. Currently it's not implemented, yet. It would probably be straightforward for the `FullLaplace` classes but other variants that rely on the Backend would be tricky since both, the BackPack and ASDL backend, do not support it currently.

**Comment by hnisonoff** [comment]
Got it -- thanks for the quick reply and explanation!

**Comment by rasmusbergpalm** [comment]
Maybe I'm missing something, but why not just let the user supply a loss function to fit? The loss function can then be MSE or -Normal.logpdf(x, mean, logvar.exp()), or any other NLL the user desires. As long as it's (double) differentiable w.r.t. the model parameters I guess it should be possible to compute the Hessian, no?

**Comment by runame** [comment]
The issue is that we don't directly compute the Hessian, but use backends ([BackPACK](https://github.com/f-dangel/backpack/) and [ASDL](https://github.com/kazukiosawa/asdfghjkl)) to compute approximations of the Hessian like the generalized Gauss-Newton (GGN) matrix. Hence, which losses we can support depends on which losses our backends support.
