### ISSUE TITLE
Two moons example

### ISSUE THREAD

**Issue by ArturPrzybysz** [AlexImmer/Laplace#88]
Hi! Thanks for publishing the library!

I am trying to visualize how laplace approx. in NN fixes predictions overconfidence using a toy dataset two moons.

I have created a small repo with my demo: [(link.)](https://github.com/ArturPrzybysz/twomoonsdemo)

I am struggling to obtain a well-behaved predictive distribution. Unlike authors of  [this paper](https://arxiv.org/abs/2002.10118), who obtained something like this:
![image](https://user-images.githubusercontent.com/22005794/154106202-a82c3e4a-343f-4a34-928a-4995a5a99ff3.png)

my confidence does not resemble the distribution of the training set (I do not have two isles of two classes high confidence, surrounded by low confidence):

![image](https://user-images.githubusercontent.com/22005794/154106657-aff1cc43-a246-4d70-a0f4-dcf03b025ef5.png)

What am I doing wrong in my code? 
I have played around with different activation functions, L and layer sizes but without success.

**Comment by runame** [comment]
Hi Artur, cool to see you playing with the library!

I wanted to try to modify your code myself before I reply, but you already found the crucial point: from our experience MC sampling works much better for small toy data classification examples than the probit approximation. I can't give you a satisfying explanation why this is the case, but we might look into it more.

**Comment by grofte** [comment]
Your confidences are almost completely flat in the BNN image. The range is about 0.5 to 0.53.

And tbh ReLU appears to work as good as Tanh and better if you increase noise to 0.2?

Changing `f = model_BNN(X)` to `f = model_BNN(X, pred_type='nn')` will make them not flat (PS finding the parameters for __call__ is a bit of a pain since they aren't in the API documentation). But then using 'kron' + 'all' looks really, really weird. But for 'last_layer' at least the values go from 0.5 to 1 even if it isn't doing what it's supposed to do. Most of the runs it is pretty bad but sometimes Laplace seems to get some luck and the "inconclusive" area is a lot bigger.
![output](https://user-images.githubusercontent.com/7976840/154706040-8f607047-d77c-4998-b173-dfdb8847650a.png)

It's still weird tho (this is with pred='nn' and batch=1 but otherwise the same as the example).

**Comment by grofte** [comment]
The striations is something to do with the mesh_dataloader. I'm not quite sure what's going on there but changing the batch to something uneven like 341 removes the vertical alignment of the stripes.

The size of the dataset should not matter though because in the article linked to they made do with 90 points: https://github.com/wiseodd/last_layer_laplace/blob/master/bnn_laplace.ipynb

If you use Mish as the activation function and mesh batch size 500 then it actually starts to look okay.
![output_mish](https://user-images.githubusercontent.com/7976840/154710054-f61cc051-39d7-4261-b4e8-c4c742006677.png)

Here is the MAP output with Mish for reference
![map_mish](https://user-images.githubusercontent.com/7976840/154710196-3f0e76fd-2bbc-4314-9681-d5fc7eb05921.png)

**Comment by grofte** [comment]
```python
def get_two_moons_np(size=300, train_size=250):
    X, y = datasets.make_moons(n_samples=size, shuffle=True, noise=0.1, random_state=1234)
    y = y.reshape(-1, 1)
    X_train, X_test, t_train, t_test = train_test_split(X, y, train_size=train_size)
    mean = np.mean(X_train, axis=0)
    std = np.std(X_train, axis=0)
    X_train = (X_train - mean) / std
    X_test = (X_test - mean) / std
    return X_train, X_test, t_train, t_test
```
Co-pilot basically wrote those changes so I am blaming it if I screwed up.

Mish activation doesn't work with 'all' weights, only 'last_layer'. But in practice neither does ReLU even if it doesn't throw an error. More worrying it that only 'kron' seems to work with the last layer. 'diag' and 'full' are both bad. 

Here's the BNN with Mish and scaled inputs:
![output_mish_scaled](https://user-images.githubusercontent.com/7976840/154725414-e4b2592d-185e-461e-9284-dda333b86dc8.png)
![map_mish_scaled](https://user-images.githubusercontent.com/7976840/154725432-45ad2bb5-840c-4316-8d2b-522b7a7e49ea.png)

**Comment by ArturPrzybysz** [comment]
@grofte There is no reason to feel embarrassed, thanks for looking into it! 
Thanks for the visualization tip, will use it for sure :)

@runame Thanks for the response. How can we look more into it?

**Comment by runame** [comment]
@ArturPrzybysz Sorry for the late follow-up. I don't think there is an obvious answer, this bascially requires research on the behavior of the MC vs. probit approximation. I will close this issue for now, feel free to open it again if you have specific questions.
